[package]
name = "driver"
version = "0.1.0"
authors = ["Thomas Koehler <basta.t.k+git@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "^0.2"
serde = { version = "^1.0", features = ["derive"] }
serde_yaml = "^0.8"
colored = "^1.7"
